class Config:

  DATA_PATH = './dataset/data.csv'
  POSITIVE_THRESHOLD = 0.204
  NEGATIVE_THRESHOLD = -0.194
  CONFIDENCE_QUANTILE_THRESHOLD = 0.05
  TIME_WINDOW = '6h'
  TRAIN_SIZE = 0.75
  NEGATIVE_RATIO_THRESHOLD = 0.317
  SENTIMENT_CHANGE_THRESHOLD = -0.063
  INTERACTION_CHANGE_THRESHOLD = 106275
  OUTPUT_DIR = 'results'
  
config = Config()
